apiVersion: v1
description: A Helm chart for Shipment Service
name: shipmentservice
version: 0.1.1
sources:
- https://dxdevop.visualstudio.com/mrpmicro/_git/code
maintainers:
- name: Parts Unlimited MRP GitHub Team
engine: gotpl
