version: 2
variables: 
  - &workdir
    /tmp/circleci
  - &branchignore
    ignore: [noci, gh-pages]
  - &dockerbuildimage
      - image: circleci/golang
  - &gradleimage
      - image: gradle:3.4.1-jdk8-alpine
  - &run-buildjava
    name: Build Service
    command: |
      cd $GIT_FOLDER &&
      gradle build
  - &run-javatestresults
    name: Copy Service Test Results
    command: |
      set -xu
      mkdir -p $TEST_REPORTS/junit/
      find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $TEST_REPORTS/junit/ \;
      #This dir contains html test output
      #mkdir -p ${TEST_REPORTS}/${GIT_FOLDER}
      #cp -r $GIT_FOLDER/build/reports/tests/* ${TEST_REPORTS}/${GIT_FOLDER}
  - &run-dockerbuild
    name: Build and Push Service Docker Image
    command: |
      TAG=$DOCKER_TAG
      if [[ "${REGISTRY_NAMEIMAGE}" == "" ]] ; then REGISTRY_NAMEIMAGE="buildci"; fi
      docker build -f ./$GIT_FOLDER/Dockerfile --build-arg port=$SERVICE_PORT --build-arg mongo_connection=mongodb://localhost/$GIT_FOLDER --build-arg VCS_REF=$CIRCLE_SHA1 --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG -t $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:latest .
      if [[ ((`echo $CIRCLE_BRANCH | grep -c "master"` > 0))]]; then 
        echo "Push to registry since it's the master branch."
        docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASS
        docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG
        docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:latest
        echo "Pushed image: " $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG " and :latest tag"
      else
        echo "Skip Docker push image since it is not the master branch."
      fi
jobs:
  orderservice:
    working_directory: *workdir
    docker: *gradleimage
    environment:
      GIT_FOLDER: OrderSrvc
      TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout
      - run: *run-buildjava 
      - run: *run-javatestresults

      # Optionally Save and store jar build artifacts
      #- run: |
      #    cp $GIT_FOLDER/build/libs/*.jar /tmp/artifacts

      #- store_artifacts:
      #    path: /tmp/artifacts
      #    destination: build

      # Upload test results to CircleCI
      - store_test_results:
          path: /tmp/test-reports/junit/

      - persist_to_workspace:
          root: OrderSrvc
          paths:
            - "Dockerfile"
            - build/libs/*

  orderservicedocker:
    working_directory: *workdir
    docker: *dockerbuildimage

    environment:
      DOCKER_IMAGE: pumrp-order
      DOCKER_TAG: 1.0.1
      SERVICE_PORT: 8080
      GIT_FOLDER: OrderSrvc

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /tmp/circleci/OrderSrvc

      - run: *run-dockerbuild

  quoteservice:
    working_directory: *workdir
    docker: *gradleimage

    environment:
      TEST_REPORTS: /tmp/test-reports 
      GIT_FOLDER: QuoteSrvc

    steps:
      - checkout
      - run: *run-buildjava 
      - run: *run-javatestresults

      # Optionally Save and store jar build artifacts
      #- run: |
      #    cp $GIT_FOLDER/build/libs/*.jar /tmp/artifacts

      #- store_artifacts:
      #    path: /tmp/artifacts
      #    destination: build

      # Upload test results
      - store_test_results:
          path: /tmp/test-reports/junit/

      - persist_to_workspace:
          root: QuoteSrvc
          paths:
            - "Dockerfile"
            - build/libs/*

  quoteservicedocker:
    working_directory: *workdir
    docker: *dockerbuildimage

    environment:
      DOCKER_IMAGE: pumrp-quote
      DOCKER_TAG: 1.0.1
      SERVICE_PORT: 8080
      GIT_FOLDER: QuoteSrvc

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /tmp/circleci/QuoteSrvc

      - run: *run-dockerbuild

  shipmentservice:
    working_directory: *workdir
    docker: *gradleimage

    environment:
      TEST_REPORTS: /tmp/test-reports
      GIT_FOLDER: ShipmentSrvc

    steps:
      - checkout
      - run: *run-buildjava 
      - run: *run-javatestresults

      # Optionally Save and store jar build artifacts
      #- run: |
      #    cp $GIT_FOLDER/build/libs/*.jar /tmp/artifacts

      #- store_artifacts:
      #    path: /tmp/artifacts
      #    destination: build

      # Upload test results
      - store_test_results:
          path: /tmp/test-reports/junit/

      - persist_to_workspace:
          root: ShipmentSrvc
          paths:
            - "Dockerfile"
            - build/libs/*

  shipmentservicedocker:
    working_directory: *workdir
    docker: *dockerbuildimage

    environment:
      DOCKER_IMAGE: pumrp-shipment
      DOCKER_TAG: 1.0.1
      SERVICE_PORT: 8080
      GIT_FOLDER: ShipmentSrvc

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /tmp/circleci/ShipmentSrvc

      - run: *run-dockerbuild

  catalogservice:
    working_directory: *workdir
    docker: *gradleimage

    environment:
      GIT_FOLDER: CatalogSrvc
      TEST_REPORTS: /tmp/test-reports

    steps:
      - checkout
      - run: *run-buildjava 
      - run: *run-javatestresults

      # Optionally Save and store jar build artifacts
      #- run: |
      #    cp $GIT_FOLDER/build/libs/*.jar /tmp/artifacts

      #- store_artifacts:
      #    path: /tmp/artifacts
      #    destination: build

      # Upload test results to CircleCI
      - store_test_results:
          path: /tmp/test-reports/junit/

      - persist_to_workspace:
          root: CatalogSrvc
          paths:
            - "Dockerfile"
            - build/libs/*

  catalogservicedocker:
    working_directory: *workdir
    docker: *dockerbuildimage

    environment:
      DOCKER_IMAGE: pumrp-catalog
      DOCKER_TAG: 1.0.1
      SERVICE_PORT: 8080
      GIT_FOLDER: CatalogSrvc

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /tmp/circleci/CatalogSrvc

      - run: *run-dockerbuild

  dealerservice:
    working_directory: *workdir
    docker:
      - image: microsoft/dotnet:1.1.2-sdk

    environment:
      SERVICE_PORT: 8080
      GIT_FOLDER: DealerService

    steps:
      - checkout

      - run:
          name: Build Service
          command: |
            echo "Building " $GIT_FOLDER
            cd $GIT_FOLDER
            dotnet restore
            dotnet build

      - persist_to_workspace:
          root: DealerService
          paths:
            - "*"
            - Models
            - Controllers

  dealerservicedocker:
    working_directory: *workdir
    docker: *dockerbuildimage

    environment:
      DOCKER_IMAGE: pumrp-dealer
      DOCKER_TAG: 1.0.1
      GIT_FOLDER: DealerService

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /tmp/circleci/DealerService

      - run: 
          name: Build and Push Service Docker Image
          command: |
            TAG=$DOCKER_TAG
            if [[ "${REGISTRY_NAMEIMAGE}" == "" ]] ; then REGISTRY_NAMEIMAGE="buildci"; fi
            echo "Building " $GIT_FOLDER
            docker build -f ./$GIT_FOLDER/Dockerfile --build-arg port=$SERVICE_PORT --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG -t $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:latest .
            if [[ ((`echo $CIRCLE_BRANCH | grep -c "master"` > 0))]]; then 
              echo "Push to registry since it's the master branch."
              docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASS
              docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG
              docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:latest
              echo "Pushed image: " $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG " and :latest tag"
            else
              echo "Skip Docker push image since it is not the master branch."
            fi

  web:
    working_directory: *workdir
    docker: *gradleimage

    environment:
      GIT_FOLDER: Web

    steps:
      - checkout

      - run: *run-buildjava 

      #- run: |
      #    cp $GIT_FOLDER/build/libs/*.jar /tmp/artifacts

      # Save artifacts
      #- store_artifacts:
      #    path: /tmp/artifacts
      #    destination: build
      - persist_to_workspace:
          root: Web
          paths:
            - "Dockerfile"
            - build/libs/*.war

  webdocker:
    working_directory: *workdir
    docker: *dockerbuildimage

    environment:
      DOCKER_IMAGE: pumrp-web
      DOCKER_TAG: 1.0.1
      GIT_FOLDER: Web
      SERVICE_PORT: 8080

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /tmp/circleci/Web

      - run:
          name: Build and Push Service Docker Image
          command: |
            echo "Building " $GIT_FOLDER
            TAG=$DOCKER_TAG
            if [[ "${REGISTRY_NAMEIMAGE}" == "" ]] ; then REGISTRY_NAMEIMAGE="buildci"; fi
            docker build -f ./$GIT_FOLDER/Dockerfile --build-arg port=$SERVICE_PORT --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG -t $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:latest .
            if [[ ((`echo $CIRCLE_BRANCH | grep -c "master"` > 0))]]; then 
              echo "Push to registry since it's the master branch."
              docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASS
              docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG
              docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:latest
              echo "Pushed image: " $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG " and :latest tag"
            else
              echo "Skip Docker push image since it is not the master branch."
            fi
workflows:
  version: 2
  build-pumrp-in-parallel:
    jobs:
      - orderservice:
          filters:
            branches: *branchignore
      - orderhold:
          type: approval
          requires: 
            - orderservice
      - orderservicedocker:
          requires:
            - orderhold
      - quoteservice:
          filters:
            branches: *branchignore
      - quotehold:
          type: approval
          requires: 
            - quoteservice
      - quoteservicedocker:
          requires:
            - quotehold
      - shipmentservice:
          filters:
            branches: *branchignore
      - shipmenthold:
          type: approval
          requires: 
            - shipmentservice
      - shipmentservicedocker:
          requires:
            - shipmenthold
      - catalogservice:
          filters: 
            branches: *branchignore
      - cataloghold:
          type: approval
          requires: 
            - catalogservice
      - catalogservicedocker:
          requires:
            - cataloghold
      - dealerservice:
          filters:
            branches: *branchignore
      - dealerhold:
          type: approval
          requires: 
            - dealerservice
      - dealerservicedocker:
          requires:
            - dealerhold
      - web:
          filters:
            branches: *branchignore
      - webhold:
          type: approval
          requires: 
            - web
      - webdocker:
          requires:
            - webhold