resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: java
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - QuoteSrvc/*

steps:
- task: Gradle@2
  displayName: 'gradlew build'
  inputs:
    gradleWrapperFile: QuoteSrvc/gradlew
    workingDirectory: QuoteSrvc

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: $(SERVICE_CONNECTION)
    azureContainerRegistry: $(ACR_SERVER)
    dockerFile: QuoteSrvc/Dockerfile
    useDefaultContext: false
    buildContext: '$(Build.SourcesDirectory)'
    addDefaultLabels: false
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: $(SERVICE_CONNECTION)
    azureContainerRegistry: $(ACR_SERVER)
    command: push